### ISSUE TITLE
Server side fetch

### ISSUE THREAD

**Issue by ilionic** [steida/songary#20]
Hey, was playing around with Firebase server side data fetching - `loadSong` from `userstate` for example. 
As I can see data is fetched on server side, passed through state and revived through `map`, but only first time route is hit. After that `listenFirebase` takes over and loads data afterwards when you switch the songs.

So what I am interested in - is it possible not to use `listenFirebase` and fetch data always on server side.  I am having troubles figuring out why state is not updating when you change routes.
for example `song/11` - state is populated with data, after I go to `song/12` - state is not updated from server side unless I hard refresh.
Thanks

**Comment by steida** [comment]
Sure. But hogher order component must be updated. The same here https://github.com/este/este/blob/master/src/common/components/fetch.js#L27

**Comment by ilionic** [comment]
Thanks a lot, makes sense. Do you have quick tip within scope of songary ( as I haven't updated to redux este ) - is principe the same or need to do quite a bit of refactor to align it to new este version?
Looks like I'll have more questions on Reactive conf :)
